version: "3.8"
services:
  dev:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/docker-src
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
