export const themes = [
  "Business and economy",
  "Crime and justice",
  "Defence",
  "Digital service performance",
  "Education",
  "Environment",
  "Government",
  "Government reference data",
  "Government spending",
  "Health",
  "Mapping",
  "Society",
  "Towns and cities",
  "Transport",
];
